version: '3.8'
services:
  alltalk-tts:
    image: joshxt/alltalk_tts:cpu
    restart: unless-stopped
    ports:
      - "7851:7851"
    volumes:
      - ./outputs:/app/outputs/
      - ./finetune/put-voice-samples-in-here:/app/finetune/put-voice-samples-in-here
      - ./dockerconfig.json:/app/confignew.json